part_fp_list: "./t2v/configs/quant/opensora/remain_fp.txt"
smooth_quant_list: ""
model:
    model_id: "opensora"
    model_type: 'opensora'  # ['sd','sdxl']
conditional: True
cfg_split: False
mixed_precision: [4,6,8]
# timestep_wise: True
calib_data:
    #path: "your path of calib data"  # fed outside through command line
    n_steps: 10    # calib_data_sample_steps = total setps // n_steps
    batch_size: 4  # used for quant param initialization
    n_samples: 10
quant:
    weight:
        quantizer:
            n_bits: 6
            channel_wise: True
            per_group: "channel" 
            channel_dim: 0
            scale_method: 'min_max'
            round_mode: 'nearest'
    activation:
        quantizer:
            n_bits: 6
            per_group: False  # use the tensor-wise 
            scale_method: 'min_max'  
            round_mode: 'nearest_ste'
            running_stat: False
            dynamic: False
            sym: False
            n_spatial_token: 1024  # for 16x512x512
            n_temporal_token: 16
            n_prompt: 120
            smooth_quant: # les: it is only for convenience to put smooth quant configs under act quantizer
                enable: False
                channel_wise_scale_type: momentum_act_max
                momentum: 0.95
                alpha: 0.6250

    grad_checkpoint: False
resume_with_w_quantized:
    path: None
