model:
    model_id: "pixart"
    model_type: 'pixart'  # ['sd','sdxl']
conditional: True
# timestep_wise: True
# mixed_precision: [2,4,8]
smooth_quant_list: ""
calib_data:
    path: "quant_models/calib_data/"
    n_steps: 20
    batch_size: 1  # used for quant param initialization
    n_samples: 32
    iters_w: 20000
    iters_a: 5000
quant:
    weight:
        optimization:
        quantizer:
            n_bits: 8
            per_group: "channel"
            scale_method: 'min_max'
            # round_mode: 'learned_hard_sigmoid'
            round_mode: 'nearest'
            timestep_wise: False
    activation:
        optimization:
        quantizer:
            n_bits: 8
            per_group: False
            scale_method: 'min_max'
            dynamic: False
            round_mode: 'nearest_ste'
            running_stat: True
            timestep_wise: False
            smooth_quant: # les: it is only for convenience to put smooth quant configs under act quantizer
                enable: False
                channel_wise_scale_type: momentum_act_max
                momentum: 0.95
                alpha: 0.3
            # softmax: 
                # n_bits: 16
                # channel_wise: False
                # scale_method: 'min_max'
                # round_mode: 'nearest'
                # always_zero: True
    grad_checkpoint: False
resume_with_w_quantized:
    path: None
